Namespace(N_min=2000, dir='/project2/depablo/walt/michrom/project/chr_05/chr_05_02', down_sampling=100, its=5, jobs=20, mode='contact_diffusion', odir='/project2/depablo/erschultz/michrom/project/chr_05/chr_05_02_copy/contact_diffusion', sparse_format=False, update_mode='eig')
Loaded xyz with shape (121, 3620, 3)
xyz load time: 183.346 s
found 20 total CPUs, 20 available CPUs, using 20
(121, 6554010)
sc_contacts size: 6.3 Gigabytes
Loaded 121 sc contacts
sc load time: 25.66 s
sc_contacts size: 6.3 Gigabytes
Iteration 0
starting gif
plot time: 61.707 s


Iteration 1
diag time: 7.471 s
distance time: 7.751 s
Using epsilon = 0.223
w [0.9999999  0.09242043 0.07353679 0.06916746 0.06723466]


order corr:  -0.84
Using k = 6
update time: 23.85 s
starting gif
starting gif
plot time: 129.385 s


Iteration 2
diag time: 7.777 s
distance time: 7.891 s
Using epsilon = 0.082
w [1.0000001  0.7170789  0.66486615 0.65422046 0.64036834]


order corr:  -0.85
Using k = 5
update time: 22.867 s
starting gif
starting gif
plot time: 131.49 s


Iteration 3
diag time: 6.937 s
distance time: 7.954 s
Using epsilon = 0.011
Traceback (most recent call last):
  File "diffusion_analysis.py", line 496, in <module>
    main()
  File "diffusion_analysis.py", line 490, in main
    contact_diffusion()
  File "diffusion_analysis.py", line 377, in contact_diffusion
    dmap.compute(5, 0.5)
RuntimeError: Eigensolver did not converge.
